# Generated by Django 3.0.8 on 2020-07-07 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Log_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('log_in_time', models.DateTimeField(blank=True, null=True)),
                ('log_out_time', models.DateTimeField(blank=True, null=True)),
                ('details_of_activity', models.TextField(blank=True, null=True)),
                ('company_admin_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company_agent')),
            ],
        ),
    ]
