# Generated by Django 3.0.8 on 2020-07-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_admin_log_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Log_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('log_in_time', models.DateTimeField(blank=True, null=True)),
                ('log_out_time', models.DateTimeField(blank=True, null=True)),
                ('details_of_activity', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
